// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:fsm/features/calendar/data/models/calendar_event_hive_model.dart';
import 'package:fsm/features/chat/data/models/chat_message_hive_model.dart';
import 'package:fsm/features/chat/data/models/chat_session_hive_model.dart';
import 'package:fsm/features/documents/data/models/document_hive_model.dart';
import 'package:fsm/features/parts/data/models/part_hive_model.dart';
import 'package:fsm/features/profile/data/models/profile_hive_model.dart';
import 'package:fsm/features/work_orders/data/models/work_log_hive_model.dart';
import 'package:fsm/features/work_orders/data/models/work_order_completion_cache_model.dart';
import 'package:fsm/features/work_orders/data/models/work_order_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CachedPartUsedModelAdapter());
    registerAdapter(CalendarEventHiveModelAdapter());
    registerAdapter(ChatMessageHiveModelAdapter());
    registerAdapter(ChatSessionHiveModelAdapter());
    registerAdapter(DocumentHiveModelAdapter());
    registerAdapter(PartHiveModelAdapter());
    registerAdapter(PartUsedHiveModelAdapter());
    registerAdapter(ProfileHiveModelAdapter());
    registerAdapter(ProfilePreferencesHiveModelAdapter());
    registerAdapter(WorkLogHiveModelAdapter());
    registerAdapter(WorkOrderCompletionCacheModelAdapter());
    registerAdapter(WorkOrderHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CachedPartUsedModelAdapter());
    registerAdapter(CalendarEventHiveModelAdapter());
    registerAdapter(ChatMessageHiveModelAdapter());
    registerAdapter(ChatSessionHiveModelAdapter());
    registerAdapter(DocumentHiveModelAdapter());
    registerAdapter(PartHiveModelAdapter());
    registerAdapter(PartUsedHiveModelAdapter());
    registerAdapter(ProfileHiveModelAdapter());
    registerAdapter(ProfilePreferencesHiveModelAdapter());
    registerAdapter(WorkLogHiveModelAdapter());
    registerAdapter(WorkOrderCompletionCacheModelAdapter());
    registerAdapter(WorkOrderHiveModelAdapter());
  }
}
