// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:fsm/features/calendar/data/models/calendar_event_hive_model.dart';
import 'package:fsm/features/documents/data/models/document_hive_model.dart';
import 'package:fsm/features/parts/data/models/part_hive_model.dart';
import 'package:fsm/features/profile/data/models/profile_hive_model.dart';
import 'package:fsm/features/work_orders/data/models/work_order_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CalendarEventHiveModelAdapter());
    registerAdapter(CustomerHiveModelAdapter());
    registerAdapter(DocumentHiveModelAdapter());
    registerAdapter(LocationHiveModelAdapter());
    registerAdapter(PartHiveModelAdapter());
    registerAdapter(PartUsedHiveModelAdapter());
    registerAdapter(ProfileHiveModelAdapter());
    registerAdapter(ProfilePreferencesHiveModelAdapter());
    registerAdapter(ServiceRequestHiveModelAdapter());
    registerAdapter(WorkLogHiveModelAdapter());
    registerAdapter(WorkOrderHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CalendarEventHiveModelAdapter());
    registerAdapter(CustomerHiveModelAdapter());
    registerAdapter(DocumentHiveModelAdapter());
    registerAdapter(LocationHiveModelAdapter());
    registerAdapter(PartHiveModelAdapter());
    registerAdapter(PartUsedHiveModelAdapter());
    registerAdapter(ProfileHiveModelAdapter());
    registerAdapter(ProfilePreferencesHiveModelAdapter());
    registerAdapter(ServiceRequestHiveModelAdapter());
    registerAdapter(WorkLogHiveModelAdapter());
    registerAdapter(WorkOrderHiveModelAdapter());
  }
}
