// Mocks generated by Mockito 5.4.6 from annotations
// in fsm/test/features/profile/presentation/blocs/profile/profile_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:either_dart/either.dart' as _i4;
import 'package:fsm/core/error/failures.dart' as _i5;
import 'package:fsm/features/profile/domain/entities/profile_entity.dart'
    as _i6;
import 'package:fsm/features/profile/domain/usecases/get_preferences_usecase.dart'
    as _i9;
import 'package:fsm/features/profile/domain/usecases/get_profile_usecase.dart'
    as _i2;
import 'package:fsm/features/profile/domain/usecases/update_preferences_usecase.dart'
    as _i10;
import 'package:fsm/features/profile/domain/usecases/update_profile_usecase.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileUseCase extends _i1.Mock implements _i2.GetProfileUseCase {
  MockGetProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileEntity>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileEntity>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.ProfileEntity>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileEntity>>);
}

/// A class which mocks [UpdateProfileUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProfileUseCase extends _i1.Mock
    implements _i8.UpdateProfileUseCase {
  MockUpdateProfileUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileEntity>> call(
          _i6.ProfileEntity? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [profile],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileEntity>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.ProfileEntity>>(
          this,
          Invocation.method(
            #call,
            [profile],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.ProfileEntity>>);
}

/// A class which mocks [GetPreferencesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetPreferencesUseCase extends _i1.Mock
    implements _i9.GetPreferencesUseCase {
  MockGetPreferencesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.ProfilePreferences>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.ProfilePreferences>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.ProfilePreferences>>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.ProfilePreferences>>);
}

/// A class which mocks [UpdatePreferencesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdatePreferencesUseCase extends _i1.Mock
    implements _i10.UpdatePreferencesUseCase {
  MockUpdatePreferencesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.ProfilePreferences>> call(
          _i6.ProfilePreferences? preferences) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [preferences],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.ProfilePreferences>>.value(
                _i7.dummyValue<_i4.Either<_i5.Failure, _i6.ProfilePreferences>>(
          this,
          Invocation.method(
            #call,
            [preferences],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.ProfilePreferences>>);
}
