import 'dart:convert';
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:fsm/features/work_orders/data/api/work_order_api_client.dart';
import 'package:fsm/features/work_orders/data/models/assign_work_order_request.dart';
import 'package:fsm/features/work_orders/data/models/reject_work_order_request.dart';
import 'package:fsm/features/work_orders/data/models/work_order_dto.dart';
import 'package:fsm/features/work_orders/data/models/work_order_grouped_images_response_dto.dart';
import 'package:fsm/features/work_orders/data/models/work_order_response.dart';
import 'package:fsm/features/work_orders/data/models/work_orders_response.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';

import 'work_order_api_client_test.mocks.dart';

@GenerateMocks([HttpClientAdapter])
void main() {
  late WorkOrderApiClient apiClient;
  late MockHttpClientAdapter mockHttpClientAdapter;
  late Dio dio;

  setUp(() {
    mockHttpClientAdapter = MockHttpClientAdapter();
    dio = Dio();
    dio.httpClientAdapter = mockHttpClientAdapter;
    apiClient = WorkOrderApiClient(dio, baseUrl: 'https://example.com/api');
  });

  const tWorkOrderDto = WorkOrderDto(
    id: 1,
    woNumber: 'WO-123',
    srId: 101,
    summary: 'Test',
    problemDescription: 'Desc',
    priority: 'Medium',
    visitDate: '2025-01-01T00:00:00.000',
    location: 'Loc',
    status: 'Assigned',
    durationDays: 1,
    durationHours: 8.0,
    createdAt: '2025-01-01T00:00:00.000',
    updatedAt: '2025-01-01T00:00:00.000',
    serviceRequest: null,
  );

  final tWorkOrderResponse = WorkOrderResponse(workOrder: tWorkOrderDto);

  void setUpMockResponse(dynamic payload, {int statusCode = 200}) {
    final responseBody = ResponseBody.fromString(
      jsonEncode(payload),
      statusCode,
      headers: {
        Headers.contentTypeHeader: [Headers.jsonContentType],
      },
    );
    when(mockHttpClientAdapter.fetch(any, any, any))
        .thenAnswer((_) async => responseBody);
  }

  group('getWorkOrders', () {
    test('should return WorkOrdersResponse when status is 200', () async {
      // Arrange
      final tResponse = WorkOrdersResponse(
        workOrders: [tWorkOrderDto],
        unassignedWorkOrders: [],
        total: 1,
        page: 1,
        pages: 1,
        unassignedCount: 0,
      );

      // Need to mirror toJson structure
      final payload =
          tResponse.toJson(); // Assuming toJson exists or manual map
      // Actually WorkOrdersResponse is generated by json_serializable usually, so call toJson() if available
      // or construct map.
      // Since we don't have access to run the code to check if toJson exists easily without verifying,
      // we assume it does because it's a model.
      // Wait, models usually have toJson generated.

      setUpMockResponse(payload);

      // Act
      final result = await apiClient.getWorkOrders(page: 1, limit: 10);

      // Assert
      expect(result, isA<WorkOrdersResponse>());
      expect(result.workOrders.length, 1);
      verify(mockHttpClientAdapter.fetch(any, any, any)).called(1);
    });
  });

  group('getWorkOrderById', () {
    test('should return WorkOrderResponse when status is 200', () async {
      // Arrange
      final payload = tWorkOrderResponse.toJson();
      setUpMockResponse(payload);

      // Act
      final result = await apiClient.getWorkOrderById(1);

      // Assert
      expect(result, isA<WorkOrderResponse>());
      expect(result.workOrder.id, 1);
    });
  });

  group('startWorkOrder', () {
    test('should send multipart request and return WorkOrderResponse',
        () async {
      // Arrange
      final payload = tWorkOrderResponse.toJson();
      setUpMockResponse(payload);

      // Act
      final result = await apiClient.startWorkOrder(
        id: 1,
        gpsCoordinates: '[0,0]',
      );

      // Assert
      expect(result, isA<WorkOrderResponse>());
      // We can also verify the method is PATCH and contains parts if we inspect the arguments to fetch
      // but verifying the call happened is often sufficient for generated code.
      verify(mockHttpClientAdapter.fetch(
        argThat(predicate((RequestOptions options) {
          return options.method == 'PATCH' &&
              options.path.contains('/work-orders/1/start') &&
              options.contentType?.contains('multipart') == true;
        })),
        any,
        any,
      ));
    });
  });

  // Adding test for generic AssignWorkOrder
  group('assignWorkOrder', () {
    test('should send body and return WorkOrderResponse', () async {
      // Arrange
      final payload = tWorkOrderResponse.toJson();
      setUpMockResponse(payload);
      final request = AssignWorkOrderRequest(assignedTo: 99);

      // Act
      final result = await apiClient.assignWorkOrder(id: 1, body: request);

      // Assert
      expect(result, isA<WorkOrderResponse>());
      verify(mockHttpClientAdapter.fetch(
        argThat(predicate((RequestOptions options) {
          return options.method == 'PATCH' &&
              options.path.contains('/work-orders/1/assign');
        })),
        any,
        any,
      ));
    });
  });

  group('pauseWorkOrder', () {
    test('should send multipart request and return WorkOrderResponse',
        () async {
      // Arrange
      final payload = tWorkOrderResponse.toJson();
      setUpMockResponse(payload);

      // Act
      final result = await apiClient.pauseWorkOrder(
        id: 1,
        reason: 'Lunch',
        gpsCoordinates: '[0,0]',
      );

      // Assert
      expect(result, isA<WorkOrderResponse>());
      verify(mockHttpClientAdapter.fetch(
        argThat(predicate((RequestOptions options) {
          return options.method == 'PATCH' &&
              options.path.contains('/work-orders/1/pause') &&
              options.contentType?.contains('multipart') == true;
        })),
        any,
        any,
      ));
    });
  });

  group('resumeWorkOrder', () {
    test('should send multipart request and return WorkOrderResponse',
        () async {
      // Arrange
      final payload = tWorkOrderResponse.toJson();
      setUpMockResponse(payload);

      // Act
      final result = await apiClient.resumeWorkOrder(
        id: 1,
        gpsCoordinates: '[0,0]',
      );

      // Assert
      expect(result, isA<WorkOrderResponse>());
      verify(mockHttpClientAdapter.fetch(
        argThat(predicate((RequestOptions options) {
          return options.method == 'PATCH' &&
              options.path.contains('/work-orders/1/resume') &&
              options.contentType?.contains('multipart') == true;
        })),
        any,
        any,
      ));
    });
  });

  group('completeWorkOrder', () {
    test('should send multipart request and return WorkOrderResponse',
        () async {
      // Arrange
      final payload = tWorkOrderResponse.toJson();
      setUpMockResponse(payload);

      final tempDir = Directory.systemTemp;
      final dummyFile = File('${tempDir.path}/dummy_sig.jpg');
      await dummyFile.writeAsString('dummy content');
      addTearDown(() => dummyFile.delete().ignore());

      // Act
      final result = await apiClient.completeWorkOrder(
        id: 1,
        workLog: 'Done',
        gpsCoordinates: '[0,0]',
        customerName: 'john',
        signature: dummyFile,
        partsUsed: '[]',
      );

      // Assert
      expect(result, isA<WorkOrderResponse>());
      verify(mockHttpClientAdapter.fetch(
        argThat(predicate((RequestOptions options) {
          return options.method == 'PATCH' &&
              options.path.contains('/work-orders/1/complete') &&
              options.contentType?.contains('multipart') == true;
        })),
        any,
        any,
      ));
    });
  });

  group('rejectWorkOrder', () {
    test('should send body and return WorkOrderResponse', () async {
      // Arrange
      final payload = tWorkOrderResponse.toJson();
      setUpMockResponse(payload);
      final request = RejectWorkOrderRequest(
        reason: 'Too far',
        gpsCoordinates: '[0,0]',
      );

      // Act
      final result = await apiClient.rejectWorkOrder(id: 1, body: request);

      // Assert
      expect(result, isA<WorkOrderResponse>());
      verify(mockHttpClientAdapter.fetch(
        argThat(predicate((RequestOptions options) {
          return options.method == 'PATCH' &&
              options.path.contains('/work-orders/1/reject');
        })),
        any,
        any,
      ));
    });
  });

  group('getGroupedImages', () {
    test('should return WorkOrderGroupedImagesResponseDto', () async {
      // Arrange
      final tGroupedImagesResponse = WorkOrderGroupedImagesResponseDto(
        workOrderId: 1,
        groupedImages: {},
        pauseCounts: [],
      );
      final payload = tGroupedImagesResponse.toJson();
      setUpMockResponse(payload);

      // Act
      final result = await apiClient.getGroupedImages(1);

      // Assert
      expect(result, isA<WorkOrderGroupedImagesResponseDto>());
      expect(result.workOrderId, 1);
      verify(mockHttpClientAdapter.fetch(
        argThat(predicate((RequestOptions options) {
          return options.method == 'GET' &&
              options.path.contains('/work-orders/1/images-grouped');
        })),
        any,
        any,
      ));
    });
  });
}
