import 'package:get_it/get_it.dart';
import 'package:injectable/injectable.dart';

import '../../features/work_orders/data/services/background_sync_service.dart';
import '../../features/work_orders/data/services/local_user_store.dart';
import 'injection.config.dart';

final GetIt getIt = GetIt.instance;

/// Injectable DI configuration
@InjectableInit(
  initializerName: 'init',
  preferRelativeImports: true,
  asExtension: true,
)
Future<void> configureDependencies(String environment) async {
  // 1) Register everything generated by injectable
  await getIt.init(environment: environment);

  // 2) Initialize offline sync once, using the Dio already in DI
  await OfflineSyncService.instance.init(
    getIt(),
    getIt<LocalUserStore>(), // resolves Dio from GetIt
  );
}

/// Environment constants
abstract class Environment {
  static const String dev = 'dev';
  static const String staging = 'staging';
  static const String prod = 'prod';
}
